---

- name: Download pip.
  get_url:
    url: "{{ pip_download_url }}"
    dest: "{{ pip_download_dest }}"
  environment:
    https_proxy: "{{ pip_proxy | default('') }}"
    #when: pip_is_installed.rc != 0

- name: Install pip.
  command: "{{ python }} {{ pip_download_dest }}/get-pip.py {{ '--proxy=' + pip_proxy if pip_proxy else '' }}"
  become: true
  #when: pip_is_installed.rc != 0

- name: Delete get-pip.py.
  file:
    state: absent
    path: "{{ pip_download_dest }}/get-pip.py"
    #when: pip_is_installed.rc != 0

