---
# we need to remove python-requests installed by distutils
# cause it conflicts with requests lib installed by pip during docker-compose install
- name: remove python-requests installed by distutils
  package:
    name: python-requests
    state: absent
  register: res
  retries: 5
  until: res is success

- include: "{{ ansible_os_family }}.yml"

- name: start docker daemon
  include: "start_docker_{{ ansible_system }}.yml"

- name: add live-restore option
  include: "docker_opts_{{ ansible_system }}.yml"

- name: Install required python modules
  pip:
    name: ['docker', 'docker-compose']

- name: Install Docker Compose.
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.5/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
