---

- name: set distro-dependent variables for RedHat/CentOS
  set_fact:
    pkg_name: "bind"
    named_conf_path: "/etc/named.conf"
    conf_dir: "/etc/named"
  when: ansible_os_family == "RedHat"

- name: set distro-dependent variables for Debian/Ubuntu
  set_fact:
    pkg_name: "bind9"
    named_conf_path: "/etc/bind/named.conf"
    conf_dir: "/etc/bind"
  when: ansible_os_family == "Debian"

- name: Install bind 9
  package:
    name: 
      - "{{ pkg_name }}"
      - bind-utils
    state: present

#- name: Create zones directory
#  file:
#    path: "{{ conf_dir }}/zones"
#    state: directory
#    mode: '0755'

- name: Add zone files
  template:
    src: "{{ item }}"
    dest: "/var/named/data/{{ item }}"
  with_items:
    - sjc1.zone
    - ca-ymq-1.zone

- name: Add common data
  copy:
    src: "{{ item }}"
    dest: "/var/named/data/{{ item }}"
  with_items:
    - common.data

- name: Add default config files
  copy:
    src: "{{ item }}"
    dest: "/etc/named/{{ item }}"
  with_items:
    - named.rfc1912.zones
    - named.root.key

- name: Generate rndc key
  shell: rndc-confgen -a -r /dev/urandom -u named

- name: Configure bind
  template:
    src: "named.conf"
    dest: "/etc/named.conf"

- name: Configure rndc
  copy:
    src: "rndc.conf"
    dest: "/etc/rndc.conf"

- name: Restart bind
  service:
    name: named
    state: restarted
